name: CI

on: [push, pull_request, workflow_dispatch]

env:
  DOCKER_REPO: godatadriven/pyspark

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        DOCKER_TAG: ["3.0.0,3.0,latest", "2.4.5,2.4"]

    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set current date as env variable
        run: echo "::set-env name=BUILD_DATE::$(date)"
        
      - name: Set spark version based on docker tag
        run: echo "::set-env name=SPARK_VERSION::${{ matrix.DOCKER_TAG }}%%,*}"

      - name: Build image
        run: docker build --build-arg BUILD_DATE="${BUILD_DATE}" --build-arg SPARK_VERSION="${SPARK_VERSION}" -t $DOCKER_REPO:${${{ matrix.DOCKER_TAG }}//,/ -t $DOCKER_REPO:} .

      - name: Test image
        run: |
            export IMAGE_NAME="$DOCKER_REPO:$SPARK_VERSION"
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut